server:
  port: 8081
spring:
  profiles:
    active: dev # 默认使用开发环境 (不加载 application-test.yaml 的参数)
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: 127.0.0.1   # 这是帮你改好的本地 Redis 地址
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    # =========================================================================
    # [面试架构展示] 哨兵(Sentinel)高可用集群配置示例
    # 架构说明：当业务流量与可用性要求增大时，废弃上方单点 host/port 配置，启用此段
    # sentinel:
    #   master: mymaster
    #   nodes:
    #     - 127.0.0.1:27001
    #     - 127.0.0.1:27002
    #     - 127.0.0.1:27003
    # =========================================================================
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
